import { Product, Category } from './types';

export const categories: Category[] = [
  {
    name: 'Infection Control',
    slug: 'infection-control',
    description: 'High efficacy virucidal, bactericidal & sporicidal disinfectants for healthcare and public health settings.',
    icon: '🛡️',
  },
  {
    name: 'Floor & Carpet Care',
    slug: 'floor-carpet',
    description: 'Shampoos, gels and disinfectants to clean and maintain all types of floors and carpets.',
    icon: '🧹',
  },
  {
    name: 'Washroom & Toilet',
    slug: 'washroom-toilet',
    description: 'Cleaning, disinfection, de-scaling and deodourising products for washrooms and toilets.',
    icon: '🚿',
  },
  {
    name: 'Animal Care',
    slug: 'animal-care',
    description: 'DEFRA-approved disinfectants for animal husbandry, kennels, stables and veterinary use.',
    icon: '🐾',
  },
  {
    name: 'Multi-Purpose Cleaners',
    slug: 'multi-purpose',
    description: 'Versatile cleaning and disinfection products suitable for a wide range of surfaces.',
    icon: '✨',
  },
  {
    name: 'Hand Care',
    slug: 'hand-care',
    description: 'Hand sanitisers, antibacterial washes and protective creams for personal hygiene.',
    icon: '🤲',
  },
  {
    name: 'Odour Control',
    slug: 'odour-control',
    description: 'Bio-enzymatic and chemical odour neutralisers and air fresheners.',
    icon: '💨',
  },
  {
    name: 'Catering & Kitchen',
    slug: 'catering-kitchen',
    description: 'Food-safe sanitisers, degreasers and dishwasher products for professional kitchens.',
    icon: '🍽️',
  },
  {
    name: 'Drain Cleaning',
    slug: 'drain-cleaning',
    description: 'Enzymatic and chemical drain cleaners and unblockers for commercial drains.',
    icon: '🔧',
  },
];

export const products: Product[] = [
  // ── Infection Control ─────────────────────────────────────────────
  {
    id: 'chloricide-5l',
    name: 'Chloricide',
    description: 'Chlorine-based broad-spectrum disinfectant. Kills bacteria, viruses, fungi and spores.',
    longDescription:
      'Chloricide is a powerful chlorine-based disinfectant trusted by healthcare professionals across the UK. It provides broad-spectrum kill against bacteria, viruses (including enveloped and non-enveloped), fungi and spores. Ideal for hard surfaces, clinical environments, care homes and food preparation areas. Dilute 1:80 for general disinfection or 1:10 for outbreak control.',
    price: 12.75,
    comparePrice: 15.99,
    size: '5L',
    category: 'Infection Control',
    categorySlug: 'infection-control',
    sku: 'SKY-IC-001',
    inStock: true,
    stockCount: 120,
    rating: 4.8,
    reviewCount: 234,
    tags: ['chlorine', 'disinfectant', 'healthcare', 'DEFRA'],
    featured: true,
    image: '🧪',
    certifications: ['EN14476', 'EN1276', 'EN13697'],
  },
  {
    id: 'chloricide-plus-5l',
    name: 'Chloricide Plus',
    description: 'Enhanced chlorine disinfectant with detergent action for one-step clean and disinfect.',
    longDescription:
      'Chloricide Plus combines the power of chlorine with a built-in detergent, allowing a single-step clean and disinfection process. Perfect for busy clinical environments where efficiency is critical. Suitable for floors, walls, sanitary ware and hard surfaces.',
    price: 14.99,
    size: '5L',
    category: 'Infection Control',
    categorySlug: 'infection-control',
    sku: 'SKY-IC-002',
    inStock: true,
    stockCount: 85,
    rating: 4.7,
    reviewCount: 189,
    tags: ['chlorine', 'disinfectant', 'detergent', 'one-step'],
    featured: true,
    image: '🧪',
    certifications: ['EN14476', 'EN1276'],
  },
  {
    id: 'viraguard-5l',
    name: 'Viraguard',
    description: 'Hospital-grade virucidal surface disinfectant. Effective against SARS-CoV-2 in 60 seconds.',
    longDescription:
      'Viraguard is a hospital-grade virucidal disinfectant proven to kill SARS-CoV-2 (COVID-19), Norovirus, Influenza and other pathogens in as little as 60 seconds. Ready-to-use formulation requires no dilution. Safe for use on most clinical surfaces, medical equipment and soft furnishings when diluted.',
    price: 18.5,
    comparePrice: 22.0,
    size: '5L',
    category: 'Infection Control',
    categorySlug: 'infection-control',
    sku: 'SKY-IC-003',
    inStock: true,
    stockCount: 67,
    rating: 4.9,
    reviewCount: 312,
    tags: ['virucidal', 'hospital-grade', 'COVID-19', 'Norovirus'],
    featured: true,
    image: '🛡️',
    certifications: ['EN14476', 'EN1276', 'EN13697', 'EN16615'],
  },
  {
    id: 'bacteriguard-5l',
    name: 'Bacteriguard',
    description: 'Quaternary ammonium bactericidal disinfectant for surfaces and equipment.',
    longDescription:
      'Bacteriguard uses quaternary ammonium compounds (QACs) to deliver effective bactericidal action against a wide spectrum of gram-positive and gram-negative bacteria. Low odour, non-tainting formula suitable for food contact surfaces when used as directed.',
    price: 15.99,
    size: '5L',
    category: 'Infection Control',
    categorySlug: 'infection-control',
    sku: 'SKY-IC-004',
    inStock: true,
    stockCount: 45,
    rating: 4.6,
    reviewCount: 98,
    tags: ['bactericidal', 'QAC', 'low-odour', 'food-safe'],
    featured: false,
    image: '🧬',
    certifications: ['EN1276', 'EN13697'],
  },
  {
    id: 'sporicide-pro-5l',
    name: 'Sporicide Pro',
    description: 'High-level sporicidal disinfectant for C. difficile and other spore-forming pathogens.',
    longDescription:
      'Sporicide Pro is formulated specifically for environments where spore-forming pathogens such as Clostridium difficile (C. diff) are a concern. Effective at low concentrations with a 10-minute contact time. Essential for care homes, hospitals and isolation areas.',
    price: 24.99,
    size: '5L',
    category: 'Infection Control',
    categorySlug: 'infection-control',
    sku: 'SKY-IC-005',
    inStock: true,
    stockCount: 30,
    rating: 4.9,
    reviewCount: 77,
    tags: ['sporicidal', 'C.diff', 'care home', 'isolation'],
    featured: false,
    image: '⚗️',
    certifications: ['EN13704', 'EN14476'],
  },

  // ── Floor & Carpet ─────────────────────────────────────────────────
  {
    id: 'carpet-shampoo-pro-5l',
    name: 'Carpet Shampoo Pro',
    description: 'Deep-clean carpet shampoo with deodourising action. Suitable for all carpet types.',
    longDescription:
      'Carpet Shampoo Pro penetrates deep into carpet fibres to lift and remove dirt, grease, stains and odours. Low-foam formula designed for use with commercial carpet cleaning machines. Leaves carpets fresh and bright. Safe for wool and synthetic carpets.',
    price: 11.99,
    size: '5L',
    category: 'Floor & Carpet Care',
    categorySlug: 'floor-carpet',
    sku: 'SKY-FC-001',
    inStock: true,
    stockCount: 90,
    rating: 4.5,
    reviewCount: 145,
    tags: ['carpet', 'shampoo', 'deodouriser', 'machine use'],
    featured: false,
    image: '🧽',
  },
  {
    id: 'floor-gel-disinfectant-5l',
    name: 'Floor Gel Disinfectant',
    description: 'Clinging gel disinfectant for hard floors. Long dwell time for maximum kill.',
    longDescription:
      'Floor Gel Disinfectant clings to floor surfaces for extended contact time, ensuring thorough disinfection of hard floors including ceramic, vinyl, concrete and wood laminates. Contains a pleasant fresh fragrance. Effective against bacteria, yeasts and enveloped viruses.',
    price: 13.5,
    size: '5L',
    category: 'Floor & Carpet Care',
    categorySlug: 'floor-carpet',
    sku: 'SKY-FC-002',
    inStock: true,
    stockCount: 75,
    rating: 4.4,
    reviewCount: 112,
    tags: ['floor', 'gel', 'disinfectant', 'hard floor'],
    featured: false,
    image: '🧹',
  },
  {
    id: 'hard-floor-polish-5l',
    name: 'Hard Floor Polish',
    description: 'Protective acrylic floor polish that adds shine and guards against scuffs and scratches.',
    longDescription:
      'Hard Floor Polish provides a durable protective coating on vinyl, marble, terrazzo and sealed wood floors. Self-levelling formula gives a brilliant, long-lasting shine. Reduces maintenance frequency by protecting the floor surface from daily wear.',
    price: 16.75,
    size: '5L',
    category: 'Floor & Carpet Care',
    categorySlug: 'floor-carpet',
    sku: 'SKY-FC-003',
    inStock: true,
    stockCount: 40,
    rating: 4.3,
    reviewCount: 67,
    tags: ['floor polish', 'acrylic', 'shine', 'protective'],
    featured: false,
    image: '✨',
  },
  {
    id: 'carpet-stain-remover-500ml',
    name: 'Carpet Stain Remover',
    description: 'Concentrated spot stain remover for carpets and upholstery. Removes toughest stains.',
    longDescription:
      'Carpet Stain Remover is a concentrated spot treatment formula designed to tackle the most stubborn stains including red wine, coffee, blood, grease and pet accidents. Safe on most carpet types and upholstery fabrics. Spray, agitate, blot dry.',
    price: 9.99,
    size: '500ml',
    category: 'Floor & Carpet Care',
    categorySlug: 'floor-carpet',
    sku: 'SKY-FC-004',
    inStock: true,
    stockCount: 150,
    rating: 4.6,
    reviewCount: 203,
    tags: ['stain remover', 'carpet', 'upholstery', 'spot treatment'],
    featured: false,
    image: '🫧',
  },

  // ── Washroom & Toilet ──────────────────────────────────────────────
  {
    id: 'dazzle-toilet-cleaner-5l',
    name: 'Dazzle',
    description: 'Powerful toilet bowl cleaner with limescale and stain removing action.',
    longDescription:
      'Dazzle is a viscous, acidic toilet bowl cleaner that clings to the bowl surface to dissolve limescale, mineral deposits and organic stains. Leaves a sparkling clean, fresh-smelling finish. Thick gel formula ensures full bowl coverage for maximum effectiveness.',
    price: 8.99,
    size: '5L',
    category: 'Washroom & Toilet',
    categorySlug: 'washroom-toilet',
    sku: 'SKY-WT-001',
    inStock: true,
    stockCount: 200,
    rating: 4.5,
    reviewCount: 178,
    tags: ['toilet', 'limescale', 'cleaner', 'gel'],
    featured: true,
    image: '🚽',
  },
  {
    id: 'deep-blue-washroom-5l',
    name: 'Deep Blue',
    description: 'Washroom disinfectant cleaner with fresh fragrance. Kills 99.999% of bacteria.',
    longDescription:
      'Deep Blue is a professional washroom disinfectant cleaner combining powerful bactericidal action with a long-lasting fresh fragrance. Cleans, disinfects and deodourises washroom surfaces including sinks, tiles, shower trays and urinals in a single application.',
    price: 11.25,
    size: '5L',
    category: 'Washroom & Toilet',
    categorySlug: 'washroom-toilet',
    sku: 'SKY-WT-002',
    inStock: true,
    stockCount: 110,
    rating: 4.7,
    reviewCount: 156,
    tags: ['washroom', 'disinfectant', 'fragrance', 'bactericidal'],
    featured: false,
    image: '🪣',
  },
  {
    id: 'saniguard-blocks-12pk',
    name: 'Saniguard Toilet Blocks',
    description: 'Long-lasting toilet and urinal rim blocks with antibacterial action. Pack of 12.',
    longDescription:
      'Saniguard Toilet Blocks deliver continuous antibacterial protection and fresh fragrance with every flush. Each block lasts up to 4 weeks. Suitable for both toilet and urinal cisterns. Reduces odours and helps prevent limescale build-up.',
    price: 6.5,
    size: 'Pack of 12',
    category: 'Washroom & Toilet',
    categorySlug: 'washroom-toilet',
    sku: 'SKY-WT-003',
    inStock: true,
    stockCount: 300,
    rating: 4.3,
    reviewCount: 89,
    tags: ['toilet block', 'urinal', 'fragrance', 'antibacterial'],
    featured: false,
    image: '🧊',
  },
  {
    id: 'descale-pro-5l',
    name: 'Descale Pro',
    description: 'Heavy-duty limescale remover for taps, showers, tiles and sanitary ware.',
    longDescription:
      'Descale Pro contains a blend of organic and inorganic acids to rapidly dissolve even the heaviest limescale, calcium and mineral deposits. Safe on chrome, stainless steel and ceramic surfaces. Dilute for light scale or use neat for heavy build-up.',
    price: 12.0,
    size: '5L',
    category: 'Washroom & Toilet',
    categorySlug: 'washroom-toilet',
    sku: 'SKY-WT-004',
    inStock: true,
    stockCount: 60,
    rating: 4.6,
    reviewCount: 134,
    tags: ['limescale', 'descaler', 'taps', 'showers'],
    featured: false,
    image: '⚡',
  },

  // ── Animal Care ────────────────────────────────────────────────────
  {
    id: 'animal-farm-disinfectant-5l',
    name: 'Animal Farm Disinfectant',
    description: 'DEFRA-approved farm and livestock disinfectant. Effective against Foot and Mouth Disease.',
    longDescription:
      'Animal Farm Disinfectant is a DEFRA-approved product for use in Foot and Mouth Disease orders and General Orders. This broad-spectrum disinfectant is effective against all major livestock pathogens. Suitable for farm buildings, vehicles, equipment and footbaths.',
    price: 22.99,
    comparePrice: 27.99,
    size: '5L',
    category: 'Animal Care',
    categorySlug: 'animal-care',
    sku: 'SKY-AC-001',
    inStock: true,
    stockCount: 55,
    rating: 4.8,
    reviewCount: 67,
    tags: ['DEFRA', 'farm', 'livestock', 'Foot and Mouth'],
    featured: true,
    image: '🐄',
    certifications: ['DEFRA Approved', 'EN1656'],
  },
  {
    id: 'kennel-fresh-5l',
    name: 'Kennel Fresh',
    description: 'Safe, effective disinfectant for kennels, catteries and pet areas. Fresh pine fragrance.',
    longDescription:
      'Kennel Fresh is specially formulated for use in kennels, catteries, pet shops and veterinary practices. Kills parvo virus, kennel cough bacteria and other pet pathogens. Safe for use around animals once dry. Pleasant pine fragrance eliminates pet odours.',
    price: 18.75,
    size: '5L',
    category: 'Animal Care',
    categorySlug: 'animal-care',
    sku: 'SKY-AC-002',
    inStock: true,
    stockCount: 42,
    rating: 4.7,
    reviewCount: 91,
    tags: ['kennel', 'cattery', 'parvovirus', 'pet safe'],
    featured: false,
    image: '🐕',
    certifications: ['EN14675'],
  },
  {
    id: 'stable-clean-5l',
    name: 'Stable Clean',
    description: 'Premium equine stable disinfectant. Safe for horses, effective against ringworm and strangles.',
    longDescription:
      'Stable Clean is a premium disinfectant designed specifically for equine environments. Effective against ringworm, strangles, equine influenza and other horse pathogens. Non-tainting formula safe to use in feed areas. Ideal for stables, horse boxes and tack rooms.',
    price: 24.99,
    size: '5L',
    category: 'Animal Care',
    categorySlug: 'animal-care',
    sku: 'SKY-AC-003',
    inStock: false,
    stockCount: 0,
    rating: 4.9,
    reviewCount: 44,
    tags: ['equine', 'stable', 'ringworm', 'strangles'],
    featured: false,
    image: '🐎',
    certifications: ['EN1276'],
  },

  // ── Multi-Purpose ──────────────────────────────────────────────────
  {
    id: 'sky-multi-clean-5l',
    name: 'Sky Multi-Clean',
    description: 'All-purpose cleaner and disinfectant for any hard surface. Safe and effective.',
    longDescription:
      'Sky Multi-Clean is the go-to all-purpose cleaner and disinfectant for busy commercial and institutional environments. Cleans and disinfects in one step. Suitable for desks, worktops, walls, floors and equipment. Lemon fresh fragrance. Ready to use.',
    price: 10.99,
    size: '5L',
    category: 'Multi-Purpose Cleaners',
    categorySlug: 'multi-purpose',
    sku: 'SKY-MP-001',
    inStock: true,
    stockCount: 180,
    rating: 4.5,
    reviewCount: 267,
    tags: ['multi-purpose', 'all-surface', 'lemon', 'ready-to-use'],
    featured: true,
    image: '🫧',
  },
  {
    id: 'sky-surface-spray-750ml',
    name: 'Sky Surface Spray',
    description: 'Ready-to-use antibacterial surface spray for quick wipe-downs. Kills 99.9% of bacteria.',
    longDescription:
      'Sky Surface Spray is a convenient trigger spray for quick antibacterial wipe-downs on any hard surface. No dilution required. Kills 99.9% of bacteria in 30 seconds. Ideal for reception desks, door handles, keyboards, phones and communal areas.',
    price: 7.5,
    size: '750ml',
    category: 'Multi-Purpose Cleaners',
    categorySlug: 'multi-purpose',
    sku: 'SKY-MP-002',
    inStock: true,
    stockCount: 250,
    rating: 4.4,
    reviewCount: 189,
    tags: ['spray', 'antibacterial', 'trigger spray', 'ready-to-use'],
    featured: false,
    image: '🧴',
  },
  {
    id: 'sky-concentrate-5l',
    name: 'Sky Concentrate',
    description: 'Super-concentrated multi-purpose cleaner. Highly economical — dilutes up to 1:200.',
    longDescription:
      'Sky Concentrate is a super-concentrated all-purpose cleaner delivering outstanding economy. Dilute at just 5ml per litre for general cleaning, making each 5L container yield up to 1,000 litres of working solution. Biodegradable formula safe for drain disposal.',
    price: 14.5,
    size: '5L',
    category: 'Multi-Purpose Cleaners',
    categorySlug: 'multi-purpose',
    sku: 'SKY-MP-003',
    inStock: true,
    stockCount: 95,
    rating: 4.6,
    reviewCount: 123,
    tags: ['concentrate', 'economical', 'biodegradable', 'multi-purpose'],
    featured: false,
    image: '💧',
  },

  // ── Hand Care ──────────────────────────────────────────────────────
  {
    id: 'hand-sanitiser-pro-500ml',
    name: 'Hand Sanitiser Pro',
    description: '70% alcohol-based hand sanitiser gel. EN1500 certified. Fast acting, moisturising.',
    longDescription:
      'Hand Sanitiser Pro contains 70% isopropyl alcohol for rapid, effective hand sanitisation. EN1500 certified for hygienic hand rub. Added moisturisers prevent skin drying with frequent use. No water or rinsing required. Suitable for healthcare, food service and general use.',
    price: 9.99,
    comparePrice: 12.5,
    size: '500ml',
    category: 'Hand Care',
    categorySlug: 'hand-care',
    sku: 'SKY-HC-001',
    inStock: true,
    stockCount: 500,
    rating: 4.7,
    reviewCount: 445,
    tags: ['hand sanitiser', '70% alcohol', 'EN1500', 'moisturising'],
    featured: true,
    image: '🤲',
    certifications: ['EN1500', 'EN12791'],
  },
  {
    id: 'antibacterial-handwash-5l',
    name: 'Antibacterial Hand Wash',
    description: 'Gentle yet effective antibacterial liquid hand soap for frequent use. Floral fragrance.',
    longDescription:
      'Antibacterial Hand Wash combines effective antibacterial action with a mild, skin-friendly formula suitable for frequent use. Contains moisturisers to maintain skin health. Ideal for wall-mounted or countertop dispensers in washrooms, kitchens and healthcare settings.',
    price: 8.5,
    size: '5L',
    category: 'Hand Care',
    categorySlug: 'hand-care',
    sku: 'SKY-HC-002',
    inStock: true,
    stockCount: 220,
    rating: 4.5,
    reviewCount: 312,
    tags: ['hand wash', 'antibacterial', 'soap', 'floral'],
    featured: false,
    image: '🧼',
  },
  {
    id: 'hand-cream-shield-250ml',
    name: 'Hand Cream Shield',
    description: 'Barrier hand cream that protects against chemicals, solvents and frequent washing.',
    longDescription:
      'Hand Cream Shield forms an invisible protective barrier on the skin, guarding against the drying effects of frequent hand washing, chemicals and solvents. Rapidly absorbed non-greasy formula. Apply before work or after washing for best protection.',
    price: 6.75,
    size: '250ml',
    category: 'Hand Care',
    categorySlug: 'hand-care',
    sku: 'SKY-HC-003',
    inStock: true,
    stockCount: 145,
    rating: 4.4,
    reviewCount: 78,
    tags: ['barrier cream', 'hand cream', 'skin protection', 'non-greasy'],
    featured: false,
    image: '💆',
  },

  // ── Odour Control ──────────────────────────────────────────────────
  {
    id: 'odour-neutraliser-5l',
    name: 'Odour Neutraliser',
    description: 'Bio-enzymatic odour neutraliser that eliminates odours at source. Not just masks them.',
    longDescription:
      'Odour Neutraliser uses bio-enzymatic technology to break down the organic compounds responsible for unpleasant odours at a molecular level. Unlike air fresheners that merely mask odours, Odour Neutraliser permanently eliminates them. Effective against urine, faeces, vomit, food and pet odours.',
    price: 13.99,
    size: '5L',
    category: 'Odour Control',
    categorySlug: 'odour-control',
    sku: 'SKY-OC-001',
    inStock: true,
    stockCount: 80,
    rating: 4.8,
    reviewCount: 167,
    tags: ['odour', 'enzymatic', 'urine', 'pet odour'],
    featured: false,
    image: '💨',
  },
  {
    id: 'air-freshener-concentrate-5l',
    name: 'Air Freshener Concentrate',
    description: 'Long-lasting concentrated air freshener. One bottle makes 50L of fresh air treatment.',
    longDescription:
      'Air Freshener Concentrate delivers a burst of long-lasting fragrance when diluted with water. At 1:10 dilution, one 5L container produces 50 litres of ready-to-use air freshener. Suitable for use with trigger sprays, misting systems and foggers. Available in several fragrances.',
    price: 11.5,
    size: '5L',
    category: 'Odour Control',
    categorySlug: 'odour-control',
    sku: 'SKY-OC-002',
    inStock: true,
    stockCount: 65,
    rating: 4.4,
    reviewCount: 98,
    tags: ['air freshener', 'concentrate', 'fragrance', 'misting'],
    featured: false,
    image: '🌸',
  },

  // ── Catering & Kitchen ─────────────────────────────────────────────
  {
    id: 'kitchen-degreaser-pro-5l',
    name: 'Kitchen Degreaser Pro',
    description: 'Heavy-duty alkaline degreaser for commercial kitchen surfaces, ovens and extract fans.',
    longDescription:
      'Kitchen Degreaser Pro is a powerful alkaline degreaser formulated to cut through the heaviest baked-on grease, carbon deposits and cooking oils. Suitable for ovens, grills, fryers, extract hoods and all kitchen surfaces. Fast-acting formula reduces labour time. Food contact safe when rinsed.',
    price: 15.99,
    size: '5L',
    category: 'Catering & Kitchen',
    categorySlug: 'catering-kitchen',
    sku: 'SKY-CK-001',
    inStock: true,
    stockCount: 70,
    rating: 4.7,
    reviewCount: 134,
    tags: ['degreaser', 'kitchen', 'oven', 'grease'],
    featured: false,
    image: '🍳',
  },
  {
    id: 'food-safe-sanitiser-5l',
    name: 'Food Safe Sanitiser',
    description: 'Quat-based food contact surface sanitiser. No rinse required at use dilution.',
    longDescription:
      'Food Safe Sanitiser is a quaternary ammonium-based sanitiser approved for use on food contact surfaces without rinsing when used at the recommended dilution. Effective against food-borne pathogens including Salmonella, Listeria and E. coli. Essential for any food preparation environment.',
    price: 12.75,
    size: '5L',
    category: 'Catering & Kitchen',
    categorySlug: 'catering-kitchen',
    sku: 'SKY-CK-002',
    inStock: true,
    stockCount: 95,
    rating: 4.8,
    reviewCount: 89,
    tags: ['food safe', 'sanitiser', 'no-rinse', 'Salmonella'],
    featured: false,
    image: '🥗',
    certifications: ['EN1276', 'EN13697'],
  },
  {
    id: 'dishwasher-rinse-aid-5l',
    name: 'Dishwasher Rinse Aid',
    description: 'Commercial dishwasher rinse aid. Ensures spotless, streak-free results every time.',
    longDescription:
      'Dishwasher Rinse Aid is specially formulated for commercial glasswashers and dishwashers. Accelerates draining and drying to deliver spot-free, streak-free glassware, cutlery and crockery. Highly concentrated — typically dosed at 1–3ml per wash cycle.',
    price: 18.99,
    size: '5L',
    category: 'Catering & Kitchen',
    categorySlug: 'catering-kitchen',
    sku: 'SKY-CK-003',
    inStock: true,
    stockCount: 55,
    rating: 4.5,
    reviewCount: 72,
    tags: ['dishwasher', 'rinse aid', 'glasswasher', 'spot-free'],
    featured: false,
    image: '🍷',
  },

  // ── Drain Cleaning ─────────────────────────────────────────────────
  {
    id: 'drain-clear-5l',
    name: 'Drain Clear',
    description: 'Bio-enzymatic drain cleaner that digests grease and organic matter. Prevents blockages.',
    longDescription:
      'Drain Clear uses concentrated bio-enzymatic technology to digest grease, fats, oils, food waste and other organic matter that accumulates in drains and pipes. Regular use prevents blockages and reduces foul odours. Safe for all pipe materials including PVC, copper and cast iron.',
    price: 14.99,
    size: '5L',
    category: 'Drain Cleaning',
    categorySlug: 'drain-cleaning',
    sku: 'SKY-DC-001',
    inStock: true,
    stockCount: 60,
    rating: 4.6,
    reviewCount: 113,
    tags: ['drain', 'enzymatic', 'grease', 'blockage prevention'],
    featured: false,
    image: '🔧',
  },
  {
    id: 'drain-blast-5l',
    name: 'Drain Blast',
    description: 'High-strength chemical drain unblocker. Clears blocked drains in minutes.',
    longDescription:
      'Drain Blast is a heavy-duty chemical drain unblocker containing a powerful blend of caustic alkalis and surfactants. Rapidly dissolves hair, grease, soap scum and organic debris to clear even the most stubborn blockages. Always follow safety instructions — this is a strong caustic product.',
    price: 19.99,
    size: '5L',
    category: 'Drain Cleaning',
    categorySlug: 'drain-cleaning',
    sku: 'SKY-DC-002',
    inStock: true,
    stockCount: 35,
    rating: 4.5,
    reviewCount: 87,
    tags: ['drain unblocker', 'caustic', 'blockage', 'heavy duty'],
    featured: false,
    image: '💥',
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(slug: string): Product[] {
  return products.filter((p) => p.categorySlug === slug);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q)) ||
      p.category.toLowerCase().includes(q)
  );
}
